# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 9999:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 5555:8080